{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "hello-world-app.fullname" . }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "hello-world-app.fullname" . }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - ipBlock:
        cidr: {{ .Values.networkPolicy.cidr }}
    ports:
    - protocol: TCP
      port: 5000
{{- end }}
